# Generated by Django 3.0.5 on 2020-04-22 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200422_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
