# Generated by Django 3.0.5 on 2020-04-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-id']},
        ),
    ]
